docker:
  image: "yegor256/rultor-image:1.9.1"
architect:
  - yegor256
assets:
  gradle.properties: yegor256/polystat-secrets#gradle.properties
  pubring.gpg: yegor256/polystat-secrets#pubring.gpg
  secring.gpg: yegor256/polystat-secrets#secring.gpg
  docker-password: yegor256/polystat-secrets#docker-password
install: |
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install --errors -Dstyle.color=never
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean install -Dinvoker.skip
    mvn clean deploy -Ppolystat -Psonatype --errors --settings ../settings.xml -Dstyle.color=never
    mkdir /tmp/polystat
    cp -R src/main/eo /tmp/polystat/objects
    cp -R src/test/eo /tmp/polystat/tests
    branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout gh-pages
    git reset --hard
    sudo git config --global --add safe.directory "$(pwd)"
    sudo /bin/bash -c "cd '$(pwd)'; git clean -fd"
    rm -rf polystat
    cp -R /tmp/polystat .
    find polystat -name '*.eo' | xargs sed -i "s/0\.0\.0/${tag}/g"
    git add polystat
    find polystat -name '*.eo' > polystat.lst
    git add polystat.lst
    git commit -am "polystat ${tag}"
    git checkout "${branch}"
    image=yegor256/j2eo
    sudo docker build "$(pwd)" --tag "${image}:${tag}"
    cat ../docker-password | sudo docker login --password-stdin --username yegor256
    sudo docker push "${image}:${tag}"
