assets:
  gradle.properties: yegor256/polystat-secrets#gradle.properties
  pubring.gpg: yegor256/polystat-secrets#pubring.gpg
  secring.gpg: yegor256/polystat-secrets#secring.gpg
  docker-password: yegor256/polystat-secrets#docker-password
docker:
  image: "iammaxim/j2eo:latest"
  as_root: true
merge:
  script: |
    echo "Merge is not implemented"
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1

    cp ../gradle.properties .
    echo "Home dir: $HOME"
    echo "Current path: $(pwd)"
    echo "Contents of home dir:"
    ls -lha /home/r
    echo "Contents of current dir:"
    ls -lha
    echo "Building Gradle project (excluding tests)..."
    ./gradlew build fatJar publish -x test --info -Dcandidates=false -PmvnPublicationVersion=${tag} -Dsigning.secretKeyRingFile=/home/r/secring.gpg
    echo "Done."

    mv "J2EO-${tag}.jar" j2eo.jar
    image=yegor256/j2eo
    sudo docker build "$(pwd)" --tag "${image}:${tag}"
    cat ../docker-password | sudo docker login --password-stdin --username yegor256
    sudo docker push "${image}:${tag}"