name: gradle

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-latest,
            macos-latest,
            windows-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Download ANTLR
        shell: bash
        run: curl -fsSL -o antlr-4.13.2-complete.jar https://www.antlr.org/download/antlr-4.13.2-complete.jar

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "9.6.0"

      - name: Build
        run: gradle build

      - name: Upload Gradle test report
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: gradle-test-report-${{ matrix.os }}
          path: build/reports/tests/test/

      - name: Upload coverage to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v5
        with:
          directory: ./build/reports/jacoco/test/
          fail_ci_if_error: false
          flags: unittests
          name: codecov-umbrella

      - name: Print J2EO test report
        shell: bash
        run: |
          cd ./src/test/resources/
          python3 ./test_report.py || python ./test_report.py
